### ISSUE TITLE
Crash while playing level

### ISSUE THREAD

**Issue by dancleaver** [aflitte1/SWE-Pachinko-Game#33]
I was playing level 1, no balls had appeared in a while, and this crash happened.

```
pygame 2.3.0 (SDL 2.24.2, Python 3.10.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
/home/dan/stuff/git/SWE-Pachinko-Game/assets/music/menu.ogg
Traceback (most recent call last):
  File "/home/dan/stuff/git/SWE-Pachinko-Game/Game.py", line 304, in <module>
    main()
  File "/home/dan/stuff/git/SWE-Pachinko-Game/Game.py", line 285, in main
    if (bnd.game_over(Screen, score, ball_count)):
  File "/home/dan/stuff/git/SWE-Pachinko-Game/src/components/Backend.py", line 138, in game_over
    update_leaderboard(CurrentLevel.num, str(score), Username.name)
  File "/home/dan/stuff/git/SWE-Pachinko-Game/src/components/leaderboard.py", line 80, in update_leaderboard
    putscore(userscore, level)
  File "/home/dan/stuff/git/SWE-Pachinko-Game/src/components/leaderboard.py", line 33, in putscore
    if int(userscore[1]) >= int(scores[level-1][ii - 1][1]):
IndexError: list index out of range
```

**Comment by clostoski** [comment]
This was an issue with the leaderboard.txt file. No longer an issue
